dsr1-fp4-b200-sglang:
  image: lmsysorg/sglang:v0.5.3rc1-cu129-b200
  model: nvidia/DeepSeek-R1-0528-FP4-V2
  model-prefix: dsr1
  runner: b200
  precision: fp4
  framework: sglang
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 128 }
    - { tp: 8, conc-start: 4, conc-end: 128 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 128 }
    - { tp: 8, conc-start: 4, conc-end: 128 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 4, conc-start: 4, conc-end: 128 }
    - { tp: 8, conc-start: 4, conc-end: 16 }

dsr1-fp4-b200-trt:
  image: nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2
  model: nvidia/DeepSeek-R1-0528-FP4-V2
  model-prefix: dsr1
  runner: b200-trt
  precision: fp4
  framework: trt
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    # If TP=4, 
    #   If CONC > 32, then EP=4
    #   If CONC >= 256, DP_ATTN=true
    - { tp: 4, conc-start: 4, conc-end: 32 }
    - { tp: 4, ep: 4, conc-start: 64, conc-end: 128 }
    - { tp: 4, ep: 4, dp-attn: true, conc-start: 256, conc-end: 256 }
    # If TP=8, 
    #   If CONC > 8, then EP=8
    #   If CONC >= 256, DP_ATTN=true
    - { tp: 8, conc-start: 4, conc-end: 8 }
    - { tp: 8, ep: 8, conc-start: 16, conc-end: 128 }
    - { tp: 8, ep: 8, dp-attn: true, conc-start: 256, conc-end: 256 }
  - isl: 1024
    osl: 8192
    search-space:
    # If TP=4, 
    #   If CONC > 32, then EP=4
    #   If CONC >= 256, DP_ATTN=true
    - { tp: 4, conc-start: 4, conc-end: 32 }
    - { tp: 4, ep: 4, conc-start: 64, conc-end: 128 }
    - { tp: 4, ep: 4, dp-attn: true, conc-start: 256, conc-end: 256 }
    # If TP=8, 
    #   If CONC > 16, then EP=8
    #   If CONC >= 256, DP_ATTN=true
    - { tp: 8, conc-start: 4, conc-end: 16 }
    - { tp: 8, ep: 8, conc-start: 32, conc-end: 128 }
    - { tp: 8, ep: 8, dp-attn: true, conc-start: 256, conc-end: 256 }
  - isl: 8192
    osl: 1024
    search-space:
    # If TP=4, 
    #   If CONC > 32, then EP=4 and DP_ATTN=true
    - { tp: 4, ep: 4, conc-start: 4, conc-end: 32 }
    - { tp: 4, ep: 4, dp-attn: true, conc-start: 64, conc-end: 256 }
    # If TP=8, 
    #   If CONC > 32, then EP=8 and DP_ATTN=true
    - { tp: 8, conc-start: 4, conc-end: 32 }
    - { tp: 8, ep: 8, dp-attn: true, conc-start: 64, conc-end: 256 }

dsr1-fp8-b200-sglang:
  image: lmsysorg/sglang:v0.5.3rc1-cu129-b200
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: b200
  precision: fp8
  framework: sglang
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }

dsr1-fp8-b200-trt:
  image: nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: b200-trt
  precision: fp8
  framework: trt
  seq-len-configs:
  # For all sequence lengths, EP=TP
  - isl: 1024
    osl: 1024
    search-space:
    # If CONC > 32, then DP_ATTN=true
    - { tp: 8, ep: 8, conc-start: 4, conc-end: 32 }
    - { tp: 8, ep: 8, dp-attn: true, conc-start: 64, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    # If CONC > 64, then DP_ATTN=true
    - { tp: 8, ep: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    # If CONC > 64, then DP_ATTN=true
    - { tp: 8, ep: 8, conc-start: 4, conc-end: 64 }

dsr1-fp8-h200-sglang:
  image: lmsysorg/sglang:v0.5.2rc2-cu126
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: h200
  precision: fp8
  framework: sglang
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 8, conc-start: 4, conc-end: 64 }

dsr1-fp8-h200-trt:
  image: nvcr.io#nvidia/tensorrt-llm/release:1.1.0rc2.post2
  model: deepseek-ai/DeepSeek-R1-0528
  model-prefix: dsr1
  runner: h200-trt
  precision: fp8
  framework: trt
  # For all sequence lengths, EP=TP
  seq-len-configs:
  - isl: 1024
    osl: 1024
    # If CONC > 64, then DP_ATTN=true
    search-space:
    - { tp: 8, ep: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    # If CONC > 64, then DP_ATTN=true
    search-space:
    - { tp: 8, ep: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    # If CONC > 32, then DP_ATTN=true
    search-space:
    - { tp: 8, ep: 8, conc-start: 4, conc-end: 32 }
    - { tp: 8, ep: 8, dp-attn: true, conc-start: 64, conc-end: 64 }

gptoss-fp4-b200-trt:
  image: nvcr.io#nvidia/tensorrt-llm/release:1.2.0rc0.post1
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: b200-trt
  precision: fp4
  framework: trt
  # For all sequence lengths, if CONC >= 256, then EP=TP and DP_ATTN=true
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 64, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 8 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, conc-start: 64, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 64, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 8 }

gptoss-fp4-b200-vllm:
  image: vllm/vllm-openai:v0.11.0
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: b200
  precision: fp4
  framework: vllm
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 8 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 8 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 4 }

gptoss-fp4-h100-vllm:
  image: vllm/vllm-openai:v0.11.0
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: h100
  precision: fp4
  framework: vllm
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 16 }

gptoss-fp4-h200-trt:
  image: nvcr.io#nvidia/tensorrt-llm/release:gpt-oss-dev
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: h200-trt
  precision: fp4
  framework: trt
  # For all sequence lengths, EP=TP, DP_ATTENTION=false
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 1, ep: 1, dp-attn: false, conc-start: 4, conc-end: 64 }
    - { tp: 2, ep: 2, dp-attn: false, conc-start: 4, conc-end: 64 }
    - { tp: 4, ep: 4, dp-attn: false, conc-start: 4, conc-end: 32 }
    - { tp: 8, ep: 8, dp-attn: false, conc-start: 4, conc-end: 8 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, ep: 1, dp-attn: false, conc-start: 4, conc-end: 64 }
    - { tp: 2, ep: 2, dp-attn: false, conc-start: 4, conc-end: 64 }
    - { tp: 4, ep: 4, dp-attn: false, conc-start: 4, conc-end: 64 }
    - { tp: 8, ep: 8, dp-attn: false, conc-start: 4, conc-end: 8 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 1, ep: 1, dp-attn: false, conc-start: 4, conc-end: 64 }
    - { tp: 2, ep: 2, dp-attn: false, conc-start: 4, conc-end: 64 }
    - { tp: 4, ep: 4, dp-attn: false, conc-start: 4, conc-end: 64 }
    - { tp: 8, ep: 8, dp-attn: false, conc-start: 4, conc-end: 8 }

gptoss-fp4-h200-vllm:
  image: vllm/vllm-openai:v0.11.0
  model: openai/gpt-oss-120b
  model-prefix: gptoss
  runner: h200
  precision: fp4
  framework: vllm
  seq-len-configs:
  - isl: 1024
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 4 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 1024
    osl: 8192
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 4 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 64 }
  - isl: 8192
    osl: 1024
    search-space:
    - { tp: 1, conc-start: 4, conc-end: 64 }
    - { tp: 2, conc-start: 4, conc-end: 64 }
    - { tp: 4, conc-start: 4, conc-end: 64 }
    - { tp: 8, conc-start: 4, conc-end: 32 }
