name: Template - gpt-oss

on:
  workflow_call:
    inputs:
      exp-name:
        required: true
        type: string
      isl:
        required: true
        type: string
      osl:
        required: true
        type: string
      max-model-len:
        required: true
        type: string
      random-range-ratio:
        required: true
        type: string

      use_h100:
        type: boolean
        required: true
      use_h200:
        type: boolean
        required: true
      use_b200:
        type: boolean
        required: true
      use_mi300x:
        type: boolean
        required: true
      use_mi325x:
        type: boolean
        required: true
      use_mi355x:
        type: boolean
        required: true

jobs:
  bmk-h100:
    if: ${{ inputs.use_h100 }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: h100
      image: 'vllm/vllm-openai:v0.10.2'
      model: 'openai/gpt-oss-120b'
      tp-list: '[2, 4, 8]'
      framework: 'vllm'
      precision: 'fp4'

  bmk-h200:
    if: ${{ inputs.use_h200 }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: h200
      image: 'vllm/vllm-openai:v0.10.2'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      framework: 'vllm'
      precision: 'fp4'

  bmk-b200:
    if: ${{ inputs.use_b200 }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: b200
      image: 'vllm/vllm-openai:v0.10.2'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      framework: 'vllm'
      precision: 'fp4'

  bmk-b200-trt:
    if: ${{ inputs.use_b200 }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: b200-trt
      image: 'nvcr.io#nvidia/tensorrt-llm/release:1.2.0rc0.post1'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      framework: 'trt'
      precision: 'fp4'

  bmk-h200-trt:
    if: ${{ inputs.use_h200 }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: h200-trt
      image: 'nvcr.io#nvidia/tensorrt-llm/release:gpt-oss-dev'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      framework: 'trt'
      precision: 'fp4'

  bmk-mi300x:
    if: ${{ inputs.use_mi300x }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi300x
      image: 'rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      framework: 'vllm'
      precision: 'fp4'

  bmk-mi325x:
    if: ${{ inputs.use_mi325x }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi325x
      image: 'rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 2, 4, 8]'
      framework: 'vllm'
      precision: 'fp4'

  bmk-mi355x:
    if: ${{ inputs.use_mi355x }}
    uses: ./.github/workflows/benchmark-tmpl.yml
    secrets: inherit
    with:
      exp-name: ${{ inputs.exp-name }}
      isl: ${{ inputs.isl }}
      osl: ${{ inputs.osl }}
      max-model-len: ${{ inputs.max-model-len }}
      random-range-ratio: ${{ inputs.random-range-ratio }}
      runner: mi355x
      image: 'rocm/7.0:rocm7.0_ubuntu_22.04_vllm_0.10.1_instinct_20250927_rc1'
      model: 'openai/gpt-oss-120b'
      tp-list: '[1, 4, 8]'
      framework: 'vllm'
      precision: 'fp4'
